export const countryToTimezoneMap: { [key: string]: string } = {
  'United States': 'America/New_York',
  'United Kingdom': 'Europe/London',
  Japan: 'Asia/Tokyo',
  India: 'Asia/Kolkata',
  Canada: 'America/Toronto',
  Australia: 'Australia/Sydney',
  Brazil: 'America/Sao_Paulo',
  Turkey: 'Europe/Istanbul',
  'South Africa': 'Africa/Johannesburg',
  Mexico: 'America/Mexico_City',
  Colombia: 'America/Bogota',
  Indonesia: 'Asia/Jakarta',
  Peru: 'America/Lima',
  Kenya: 'Africa/Nairobi',
  Singapore: 'Asia/Singapore',
  Taiwan: 'Asia/Taipei',
  Iran: 'Asia/Tehran',
  Russia: 'Europe/Moscow',
  Argentina: 'America/Argentina/Buenos_Aires',
  'New Zealand': 'Pacific/Auckland',
  Pakistan: 'Asia/Karachi',
  Switzerland: 'Europe/Zurich',
  Norway: 'Europe/Oslo',
  France: 'Europe/Paris',
  Spain: 'Europe/Madrid',
  Germany: 'Europe/Berlin',
  UAE: 'Asia/Dubai',
  'South Korea': 'Asia/Seoul',
  Cuba: 'America/Havana',
  Egypt: 'Africa/Cairo',
};
